### ISSUE TITLE
Unable to craft recioes

### ISSUE THREAD

**Issue by Twistdmetal** [ArtixAllMighty/Rpg-Addon-Beastmaster#2]
using the 1.12 version, unable to craft any recipe from this mod- only able to get the items via creative mode- checked the crafting recipes on this site and found them, copied the steps correctly, but nothing shows up in the crafted window-
Using:
RPG Inventory and all class armor mods
Just enough Items
roguelike dungeons
Xaeros minimap and map,
Ruins
Personal Cars
Logical Drops
Custom Loot

**Comment by AbsolemJackdaw** [comment]
Does Just Enough Items show the recipes ?

**Comment by CharCharthemonkey** [comment]
nope JEI does not show any recipes at all for any of the RPG mods

**Comment by AbsolemJackdaw** [comment]
that is very weird. did you get the mods from the official curse forge page ? 
do you have a log to show me ? you don't need to load a world. recipes cn be faultive (which i doubt here) but if so, a log would show that

**Comment by AbsolemJackdaw** [comment]
found the problem, fixed it. thanks for the report !
