### ISSUE TITLE
in 1.12-1.1.2.0 Beastmaster mod

### ISSUE THREAD

**Issue by CharCharthemonkey** [ArtixAllMighty/Rpg-Addon-Beastmaster#3]
everytime i summon a pet (spider so far) and use it to kill something it crashes the game with no crashlog

**Comment by AbsolemJackdaw** [comment]
i doubt it has no crashlog... are you looking in the correct location ? 

[DriveNumber]:\Users\[UserName]\AppData\Roaming\.minecraft\logs\latest.log ?

Let me start up my dev environement and test that bug. I'll get back to you asap.

**Comment by AbsolemJackdaw** [comment]
Located the problem. 
When tameable  entities kill mobs, the victims drop exp, Rpg Inventory hooks into the exp drop event to calculate an evnentual boost from the emerald necklace. The abscence of a null check wether the mob was actually killed by a player is what causes the crash. 

expect an update in RpgInventory soon !
